# Generated by Django 5.1.6 on 2025-10-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='image/')),
                ('details', models.CharField(max_length=255)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=255)),
                ('photo_user', models.ImageField(default='image/default-avatar-icon-of-social-media-user-vector.jpg', upload_to='image/')),
                ('mail', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myblog.articles')),
                ('likeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeur', to='myblog.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commantaire', models.CharField(max_length=255)),
                ('date_cmt', models.DateTimeField(auto_now_add=True)),
                ('arti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='myblog.articles')),
                ('user_cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cmt', to='myblog.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='autheur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='myblog.utilisateur'),
        ),
    ]
